version: "3.8"
services:
  api_c:
    build: ./apits
    container_name: api_c
    ports:
      - "4000:4000"
      - "9229:9229"
    volumes:
      - ./apits:/app
      - /app/node_modules
    init: true
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx_c:
    container_name: nginx_c
    image: nginx:stable-alpine
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./nginx/templates:/etc/nginx/templates"
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_HOST=slowtest.ml
    restart: unless-stopped
    depends_on:
      - api_c
    extra_hosts:
      - "host.docker.internal:host-gateway"

  certbot_c:
    image: certbot/certbot
    container_name: certbot_c
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
